### ISSUE TITLE
Default configuration causes crash in Brickserver due to no OAuth configuration

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/brick-server#6]
I'm trying with a fresh clone of the repository, and am using the default `docker-compose.yml` and `configs.json` that are copied from the provided template files. Running `docker-compose up` results in the following error in the `brickserver` trace:

```
brickserver             | [2020-06-24 21:04:45 +0000] [1] [INFO] Starting gunicorn 19.9.0
brickserver             | [2020-06-24 21:04:45 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
brickserver             | [2020-06-24 21:04:45 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
brickserver             | [2020-06-24 21:04:45 +0000] [10] [INFO] Booting worker with pid: 10
brickserver             | [2020-06-24 21:04:45 +0000] [11] [INFO] Booting worker with pid: 11
brickserver             | [2020-06-24 21:04:45 +0000] [12] [INFO] Booting worker with pid: 12
brickserver             | [2020-06-24 21:04:45 +0000] [13] [INFO] Booting worker with pid: 13
brickserver             | [2020-06-24 21:04:45 +0000] [14] [INFO] Booting worker with pid: 14
brickserver             | [2020-06-24 21:04:45 +0000] [15] [INFO] Booting worker with pid: 15
brickserver             | [2020-06-24 21:04:45 +0000] [10] [ERROR] Exception in worker process
brickserver             | Traceback (most recent call last):
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
brickserver             |     worker.init_process()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/uvicorn/workers.py", line 57, in init_process
brickserver             |     super(UvicornWorker, self).init_process()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
brickserver             |     self.load_wsgi()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
brickserver             |     self.wsgi = self.app.wsgi()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
brickserver             |     self.callable = self.load()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
brickserver             |     return self.load_wsgiapp()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
brickserver             |     return util.import_app(self.app_uri)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
brickserver             |     __import__(module)
brickserver             |   File "/app/main.py", line 3, in <module>
brickserver             |     from brick_server import app
brickserver             |   File "/app/brick_server/__init__.py", line 8, in <module>
brickserver             |     from .services.entities import entity_router
brickserver             |   File "/app/brick_server/services/entities.py", line 18, in <module>
brickserver             |     from .models import Entity, Relationships, EntityIds, Entities, IsSuccess
brickserver             |   File "/app/brick_server/services/models.py", line 7, in <module>
brickserver             |     from ..auth.authorization import auth_scheme
brickserver             |   File "/app/brick_server/auth/authorization.py", line 30, in <module>
brickserver             |     google_config = configs['auth']['oauth_connections']['google']
brickserver             | KeyError: 'google'
brickserver             | [2020-06-24 21:04:45 +0000] [10] [INFO] Worker exiting (pid: 10)
brickserver             | {"loglevel": "\"debug\"", "workers": 12, "bind": "0.0.0.0:80", "workers_per_core": 1.0, "host": "0.0.0.0", "port": "80"}
```

If I remove the `oauth_connections` entry from the `configs.json` file, then I get this error:

```
brickserver             | [2020-06-24 21:05:47 +0000] [10] [ERROR] Exception in worker process
brickserver             | Traceback (most recent call last):
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
brickserver             |     worker.init_process()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/uvicorn/workers.py", line 57, in init_process
brickserver             |     super(UvicornWorker, self).init_process()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
brickserver             |     self.load_wsgi()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
brickserver             |     self.wsgi = self.app.wsgi()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
brickserver             |     self.callable = self.load()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
brickserver             |     return self.load_wsgiapp()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
brickserver             |     return util.import_app(self.app_uri)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
brickserver             |     __import__(module)
brickserver             |   File "/app/main.py", line 3, in <module>
brickserver             |     from brick_server import app
brickserver             |   File "/app/brick_server/__init__.py", line 12, in <module>
brickserver             |     from .auth.auth_server import auth_router
brickserver             |   File "/app/brick_server/auth/auth_server.py", line 13, in <module>
brickserver             |     from .authorization import FRONTEND_APP, oauth, _get_user, authenticated, _jwt_pub_key
brickserver             | ImportError: cannot import name 'oauth' from 'brick_server.auth.authorization' (/app/brick_server/auth/authorization.py)
brickserver             | [2020-06-24 21:05:47 +0000] [10] [INFO] Worker exiting (pid: 10)
```

It looks like the root cause is that `auth_server.py` imports `oauth` from `authorization.py` without ever checking that it is defined

**Comment by s0301132** [comment]
I have same error log before but when I remove both `oauth_connections` and `frontend` in `config.json` this error log is gone, I think both oauth_connections and frontend may cause this problem when build up the brickserver container.

**Comment by gtfierro** [comment]
Thanks! I eventually got your suggestion to work for me --- because the docker-compose file here uses images instead of building from source, I ran into some troubles with old cached versions of the Docker images still being around and not being updated. Changes I made to the local repository didn't take either because they aren't actually built/touched by the docker-compose setup. If docker-compose is going to be used here, it would be great if it actually built the images whose source code is contained in the repository so that this kind of debugging is a little easier. Should be a simple change

**Comment by gtfierro** [comment]
In the past 10 minutes I seem to have broken it again...still getting the `oauth` import error. I'll do some more experimenting today to see if I can reproduce

**Comment by s0301132** [comment]
@gtfierro may be you remove your original docker images and install it again? When I re-compose the images I face the same error

**Comment by gtfierro** [comment]
Oh, good idea! I clean the brickserver containers out with the following

```
docker ps -a | grep brickserver | awk '{print $1}' | xargs docker rm
```

which allows me to reproduce the error you are seeing in #5

**Comment by jbkoh** [comment]
@gtfierro @s0301132 As a workaround, I will put `oauth=None` in case it's not defined in the config file, assuming the user will not going to use related features (which I think is fine.)

I will update this repo to the gitlab repo soon as well as cleaning up the Dockerfile and config files.

Sorry for the inconvenience.
